services:
  backend-test:
    profiles:
      - backend-test
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    networks:
      - backend
    depends_on:
      - database
    command: npm run test

  frontend-test:
    profiles:
      - frontend-test
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    command: npm run check

  database:
    profiles:
      - backend-test
    image: redis
    volumes:
      - db-data:/data
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
